Bugfix:Fix missing call to grgit.open()
Fix missing call to grgit.open(), causing "Caused by:
java.lang.NullPointerException: Cannot invoke method status() on null
object"